version: '3.9'

services:

  project-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance-service-db
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: keycloak-db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command:
      - "-v start-dev"
      - "--http-port=9999"
      - "--import-realm"
    ports:
      - "9999:9999"
    environment:
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 1
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak-db
      KEYCLOAK_ADMIN: root
      KEYCLOAK_ADMIN_PASSWORD: 1
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      - keycloak-db

  finance-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      KEYCLOAK_URL: http://keycloak:9999
      KEYCLOAK_REALM: finance-service-realm
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://project-db:5432/finance-service-db
    depends_on:
      - project-db
      - keycloak

