CREATE TABLE balance
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount        DECIMAL,
    user_owner_id BIGINT,
    CONSTRAINT pk_balance PRIMARY KEY (id)
);

CREATE TABLE balance_transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance_id       BIGINT                                  NOT NULL,
    category_id      BIGINT                                  NOT NULL,
    amount           DECIMAL                                 NOT NULL,
    transaction_date BIGINT                                  NOT NULL,
    CONSTRAINT pk_balance_transaction PRIMARY KEY (id)
);

CREATE TABLE category
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_type VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    user_owner_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE piggy_bank
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount        DECIMAL,
    name          VARCHAR(255),
    purpose       VARCHAR(255),
    user_owner_id BIGINT,
    CONSTRAINT pk_piggy_bank PRIMARY KEY (id)
);

CREATE TABLE service_user
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance_id        BIGINT,
    username          VARCHAR(255)                            NOT NULL,
    created_timestamp BIGINT,
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    email             VARCHAR(255),
    currency          VARCHAR(255),
    CONSTRAINT pk_service_user PRIMARY KEY (id)
);

ALTER TABLE balance
    ADD CONSTRAINT uc_balance_user_owner UNIQUE (user_owner_id);

ALTER TABLE service_user
    ADD CONSTRAINT uc_service_user_balance UNIQUE (balance_id);

ALTER TABLE service_user
    ADD CONSTRAINT uc_service_user_username UNIQUE (username);

ALTER TABLE balance
    ADD CONSTRAINT FK_BALANCE_ON_USER_OWNER FOREIGN KEY (user_owner_id) REFERENCES service_user (id);

ALTER TABLE balance_transaction
    ADD CONSTRAINT FK_BALANCE_TRANSACTION_ON_BALANCE FOREIGN KEY (balance_id) REFERENCES balance (id);

ALTER TABLE balance_transaction
    ADD CONSTRAINT FK_BALANCE_TRANSACTION_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_ON_USER_OWNER FOREIGN KEY (user_owner_id) REFERENCES service_user (id);

ALTER TABLE piggy_bank
    ADD CONSTRAINT FK_PIGGY_BANK_ON_USER_OWNER FOREIGN KEY (user_owner_id) REFERENCES service_user (id);

ALTER TABLE service_user
    ADD CONSTRAINT FK_SERVICE_USER_ON_BALANCE FOREIGN KEY (balance_id) REFERENCES balance (id);